### ISSUE TITLE
EventMachine issues?

### ISSUE THREAD

**Issue by aronchick** [tasermonkey/ruby-nginx-sinatra-thin-websockets#1]
Have you seen this error at all?

```
$ thin -R config.ru start
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
127.0.0.1 - - [11/May/2015:12:06:36 -0700] "GET / HTTP/1.1" 200 2785 0.0136
2015-05-11 12:06:37 - NameError - uninitialized constant EventMachine::WebSocket::HandlerFactory:
```

I've required 'em-websocket' and 'sinatra-websocket' ... am I missing something else?

**Comment by tasermonkey** [comment]
Not sure... it sort of just worked for me.  Did you find out anything else?  This was me learning how to setup a stack for a client.

**Comment by aronchick** [comment]
I honestly can't remember how I solved this - I think I just pried event machine out of the mix.
